### Get Teachers List
GET http://localhost:5000/teachers/ HTTP/1.1

### GET Teachers List with their subjects lists
GET http://localhost:5000/teachers/full

### GET Teacher Subjects List
GET http://localhost:5000/teachers/full
    ?teacher=max

### GET Teachers List with subjects lists for perticular class or section
GET http://localhost:5000/teachers/full
    ?section=D
    &class=10
    &teacher=max


### Add New Teacher
POST http://localhost:5000/teachers/ HTTP/1.1
content-type: application/json

{
    "teacher_name": "hello world"
}

### Delete teacher with id
DELETE http://localhost:5000/teachers/20 HTTP/1.1

### Delete teacher with name
DELETE http://localhost:5000/teachers/ HTTP/1.1
content-type: application/json

{
    "teacher_name": "hello world"
}



